version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
       condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: flightradardb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      DASH_PORT: 8070
    ports:
      - "8070:8070"
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: flightradardb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -h localhost -d flightradardb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  cron_log:
